services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  logistics-service:
    build:
      context: services/logistics
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    depends_on:
      - kafka
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - KAFKA_URL=kafka:29092

  standard-service:
    build:
      context: services/standard
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    depends_on:
      - kafka
    environment:
      - KAFKA_URL=kafka:29092

  express-service:
    build:
      context: services/express
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    depends_on:
      - kafka
    environment:
      - KAFKA_URL=kafka:29092

  international-service:
    build:
      context: services/international
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    depends_on:
      - kafka
    environment:
      - KAFKA_URL=kafka:29092

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    depends_on:
      - kafka
    environment:
      - KAFKA_URL=kafka:29092
